# Generated by Django 6.0.4 on 2026-05-04 06:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_create_default_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='frameworks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list),
        ),
    ]
