# Generated by Django 6.0.4 on 2026-05-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        ('project', '0005_remove_template_is_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='project.project'),
        ),
    ]
