# Generated by Django 6.0.4 on 2026-05-04 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_activitylog_project'),
        ('notification', '0002_alter_notification_project'),
        ('project', '0005_remove_template_is_system'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
